import type { DetectedProblem } from "./platforms";
import {
  type AttemptCaptureRuntimeMessage,
  problemIdentityKey,
} from "./attemptCapture";
import type { UiHintMessage } from "./uiHint";
import { normalizeTrustedVerdictText } from "@/lib/capture/verdictTaxonomy";
import {
  diagnosticSubmitEpochResponse,
  LEETCODE_SUBMIT_EPOCH_CONFIRMED,
  LEETCODE_SUBMIT_EPOCH_STARTED,
  parseLeetCodeSubmitEpochControlMessage,
  SUBMIT_EPOCH_MAX_ENTRIES,
  SUBMIT_EPOCH_TTL_MS,
  type LeetCodeSubmitEpochControlMessage,
  type SubmitEpochControlResponse,
  type SubmitEpochDiagnostic,
} from "./submitEpochControl";

export type CaptureContentRuntimeDependencies = {
  readonly detectProblem: () => DetectedProblem | null;
  readonly detectVerdict: () =>
    | {
      readonly verdict: string | null;
      readonly sourceDocumentId?: string;
      readonly verdictSurface?: unknown;
    }
    | null
    | undefined;
  readonly exactResultPage: (
    detected: DetectedProblem,
  ) => boolean;
  readonly now: () => string;
  readonly activeDocumentId?: string;
};

export type CaptureContentRuntime = {
  readonly start: () => readonly AttemptCaptureRuntimeMessage[];
  readonly locationObserved: () => readonly AttemptCaptureRuntimeMessage[];
  readonly documentMutated: () => readonly AttemptCaptureRuntimeMessage[];
  readonly uiHintObserved: () => readonly UiHintMessage[];
  readonly uiHintVisible: () => readonly UiHintMessage[];
  readonly pageHidden: () => readonly AttemptCaptureRuntimeMessage[];
  readonly pageShown: () => readonly AttemptCaptureRuntimeMessage[];
  /**
   * Strict control-message boundary.  The returned array contains only
   * runtime candidate messages; identities never appear in diagnostics.
   */
  readonly controlMessageReceived: (
    message: unknown,
  ) => readonly AttemptCaptureRuntimeMessage[];
  /** Consume the fixed diagnostic generated by the previous control call. */
  readonly takeControlDiagnostic: () => SubmitEpochDiagnostic | undefined;
  /** Identity-free response helper used by content.ts. */
  readonly controlMessageResponse: () => SubmitEpochControlResponse;
};

type RuntimeState = {
  readonly detected: DetectedProblem | null;
  // The verdict span most recently observed by `detectVerdict`. `null`
  // records an explicit Waiting/Judging/null phase (transition evidence).
  readonly lastVerdictSnapshot?:
    | { readonly verdict: string | null; readonly observedAt: string };
  // Whether the last observed page state was an exact result document.
  // Used to recognize a real transition when the document identity flips.
  readonly lastExactResultActive?: boolean;
  readonly lastExactResultVerdict?: string;
};

type ArmedVerdictObservation = Readonly<{
  readonly available: boolean;
  readonly verdict: string | null;
  readonly surface: Element | null | undefined;
}>;

type EpochBaseline = Readonly<{
  /** False means the detector did not return an observation object. */
  readonly captured: boolean;
  /** A null verdict is a legitimate captured null phase. */
  readonly verdict: string | null;
  /** Undefined means a non-null verdict had no narrow DOM surface. */
  readonly surface: Element | null | undefined;
}>;

type SubmitEpoch = Readonly<{
  readonly problemExternalId: string;
  readonly submitRequestId: string;
  readonly receivedAt: string;
  readonly baseline: EpochBaseline;
  /** A later same-problem E1 owns the document transition exclusively. */
  readonly superseded: boolean;
  readonly confirmedAt?: string;
  readonly proofObserved: boolean;
  readonly emitted: boolean;
}>;

type ActionEpoch = Readonly<{
  readonly problemExternalId: string;
  readonly observedAt: string;
  readonly baseline: EpochBaseline;
}>;

function isNarrowDomSurface(surface: unknown): surface is Element {
  if (typeof Element === "undefined" || !(surface instanceof Element)) return false;
  // Generic document containers are explicitly outside the adapter-owned
  // LeetCode verdict surface contract.
  return surface !== surface.ownerDocument.body
    && surface !== surface.ownerDocument.documentElement;
}

function canonicalNow(dependencies: CaptureContentRuntimeDependencies): string {
  return dependencies.now();
}

/**
 * Verdict-gated capture runtime with a bounded, in-memory LeetCode submit
 * epoch registry.  The passive V3 detector remains intact for compatibility;
 * armed epochs are evaluated before its text-only dedupe.
 */
export function createCaptureContentRuntime(
  dependencies: CaptureContentRuntimeDependencies,
): CaptureContentRuntime {
  let state: RuntimeState = { detected: null };
  const epochs = new Map<string, SubmitEpoch>();
  const actionEpochs = new Map<string, ActionEpoch>();
  let actionEpochSequence = 0;
  let pendingDiagnostic: SubmitEpochDiagnostic | undefined;

  function reportDiagnostic(reason: SubmitEpochDiagnostic): void {
    pendingDiagnostic = reason;
  }

  function currentVerdictSnapshot(): {
    readonly verdict: string | null;
    readonly sourceDocumentId?: string;
    readonly verdictSurface?: unknown;
  } | null {
    const verdict = dependencies.detectVerdict();
    if (verdict === null || verdict === undefined) return null;
    return {
      verdict: verdict.verdict,
      ...(verdict.sourceDocumentId === undefined ? {} : { sourceDocumentId: verdict.sourceDocumentId }),
      ...(verdict.verdictSurface === undefined ? {} : { verdictSurface: verdict.verdictSurface }),
    };
  }

  function armedObservation(): ArmedVerdictObservation {
    const snapshot = currentVerdictSnapshot();
    if (snapshot === null) return { available: false, verdict: null, surface: undefined };
    if (snapshot.verdict === null) return { available: true, verdict: null, surface: null };
    const normalized = normalizeTrustedVerdictText(snapshot.verdict);
    const surface = isNarrowDomSurface(snapshot.verdictSurface)
      ? snapshot.verdictSurface
      : undefined;
    return {
      available: true,
      verdict: normalized,
      surface,
    };
  }

  function clearEpochs(): void {
    epochs.clear();
    actionEpochs.clear();
  }

  function pruneExpiredEpochs(nowValue?: string): void {
    const now = nowValue ?? canonicalNow(dependencies);
    const nowMs = Date.parse(now);
    if (!Number.isFinite(nowMs)) return;
    for (const [requestId, epoch] of epochs) {
      const receivedMs = Date.parse(epoch.receivedAt);
      if (!Number.isFinite(receivedMs) || nowMs >= receivedMs + SUBMIT_EPOCH_TTL_MS) {
        epochs.delete(requestId);
      }
    }
    for (const [observedAt, epoch] of actionEpochs) {
      const observedMs = Date.parse(epoch.observedAt);
      if (!Number.isFinite(observedMs) || nowMs >= observedMs + SUBMIT_EPOCH_TTL_MS) {
        actionEpochs.delete(observedAt);
      }
    }
  }

  function observeDetectedProblem(): void {
    const detected = dependencies.detectProblem();
    if (detected === null) {
      clearEpochs();
      state = { ...state, detected: null, lastExactResultActive: undefined };
      return;
    }
    const same = state.detected !== null
      && problemIdentityKey(detected) === problemIdentityKey(state.detected);
    if (!same) {
      clearEpochs();
      state = { ...state, detected, lastExactResultActive: undefined };
    }
  }

  function hasEpochMarkerForDetectedProblem(): boolean {
    return state.detected?.platform === "leetcode"
      && ([...epochs.values()].some((epoch) =>
        epoch.problemExternalId === state.detected?.problemExternalId)
        || [...actionEpochs.values()].some((epoch) =>
          epoch.problemExternalId === state.detected?.problemExternalId));
  }

  function baselineFromObservation(): EpochBaseline {
    const snapshot = currentVerdictSnapshot();
    if (snapshot === null) {
      return { captured: false, verdict: null, surface: undefined };
    }
    if (snapshot.verdict === null) {
      return { captured: true, verdict: null, surface: null };
    }
    const normalized = normalizeTrustedVerdictText(snapshot.verdict);
    const surface = isNarrowDomSurface(snapshot.verdictSurface)
      ? snapshot.verdictSurface
      : undefined;
    if (surface === undefined) {
      return { captured: false, verdict: normalized, surface: undefined };
    }
    return { captured: true, verdict: normalized, surface };
  }

  function addStartedEpoch(message: Extract<LeetCodeSubmitEpochControlMessage, { readonly type: typeof LEETCODE_SUBMIT_EPOCH_STARTED }>): void {
    const existing = epochs.get(message.submitRequestId);
    if (existing !== undefined) {
      if (existing.problemExternalId !== message.problemExternalId) {
        reportDiagnostic("epoch_identity_conflict");
      } else if (existing.receivedAt !== message.receivedAt) {
        reportDiagnostic("epoch_timestamp_conflict");
      }
      return;
    }
    // Same-problem epochs are exclusive even when the bounded registry is
    // full. Mark the prior active epoch terminal before rejecting this new
    // E1, so a rejected B cannot leave A armed for a later DOM transition.
    for (const [requestId, prior] of epochs) {
      if (prior.problemExternalId !== message.problemExternalId
        || requestId === message.submitRequestId
        || prior.superseded) continue;
      epochs.set(requestId, { ...prior, superseded: true });
    }
    if (epochs.size >= SUBMIT_EPOCH_MAX_ENTRIES) {
      reportDiagnostic("epoch_capacity_exceeded");
      return;
    }
    if (state.detected === null
      || state.detected.platform !== "leetcode"
      || state.detected.problemExternalId !== message.problemExternalId) {
      // An exact E1 may arrive before a same-document detector tick.  Keep
      // the epoch only when the current problem identity is already known;
      // otherwise it cannot legally establish a DOM baseline.
      reportDiagnostic("epoch_baseline_missing");
      epochs.set(message.submitRequestId, {
        problemExternalId: message.problemExternalId,
        submitRequestId: message.submitRequestId,
        receivedAt: message.receivedAt,
        baseline: { captured: false, verdict: null, surface: undefined },
        superseded: false,
        proofObserved: false,
        emitted: false,
      });
      return;
    }
    const eligibleActions = [...actionEpochs.values()]
      .filter((action) => action.problemExternalId === message.problemExternalId
        && Date.parse(action.observedAt) <= Date.parse(message.receivedAt));
    if (eligibleActions.length === 0) {
      reportDiagnostic("epoch_started_missing");
      return;
    }
    if (eligibleActions.length !== 1) {
      reportDiagnostic("epoch_identity_conflict");
      return;
    }
    const action = eligibleActions[0];
    if (action === undefined) {
      reportDiagnostic("epoch_started_missing");
      return;
    }
    const baseline = action.baseline;
    for (const [observedAt, action] of actionEpochs) {
      if (action.problemExternalId === message.problemExternalId) actionEpochs.delete(observedAt);
    }
    epochs.set(message.submitRequestId, {
      problemExternalId: message.problemExternalId,
      submitRequestId: message.submitRequestId,
      receivedAt: message.receivedAt,
      baseline,
      superseded: false,
      proofObserved: false,
      emitted: false,
    });
    if (!baseline.captured) reportDiagnostic("epoch_baseline_missing");
  }

  function promoteActionEpoch(
    message: Extract<LeetCodeSubmitEpochControlMessage, { readonly type: typeof LEETCODE_SUBMIT_EPOCH_CONFIRMED }>,
  ): SubmitEpoch | undefined {
    if (message.actionObservedAt === undefined || message.baselineSubmissionIds === undefined) {
      reportDiagnostic("epoch_started_missing");
      return undefined;
    }
    const candidates = [...actionEpochs.values()].filter((action) =>
      action.problemExternalId === message.problemExternalId
      && Date.parse(action.observedAt) <= Date.parse(message.confirmedAt));
    if (candidates.length === 0) {
      reportDiagnostic("epoch_started_missing");
      return undefined;
    }
    if (candidates.length !== 1) {
      reportDiagnostic("epoch_identity_conflict");
      return undefined;
    }
    const action = candidates[0];
    if (action === undefined) {
      reportDiagnostic("epoch_started_missing");
      return undefined;
    }
    if (action.problemExternalId !== message.problemExternalId) {
      reportDiagnostic("epoch_identity_conflict");
      return undefined;
    }
    if (action.observedAt !== message.actionObservedAt) {
      reportDiagnostic("epoch_identity_conflict");
      return undefined;
    }
    if (Date.parse(message.confirmedAt) < Date.parse(action.observedAt)) {
      reportDiagnostic("epoch_timestamp_conflict");
      return undefined;
    }
    if (action.baseline.surface !== null
      && action.baseline.surface !== undefined
      && message.baselineSubmissionIds.length === 0) {
      reportDiagnostic("epoch_baseline_missing");
      return undefined;
    }
    if (epochs.size >= SUBMIT_EPOCH_MAX_ENTRIES) {
      reportDiagnostic("epoch_capacity_exceeded");
      return undefined;
    }
    for (const [observedAt, stored] of actionEpochs) {
      if (stored.problemExternalId === message.problemExternalId) actionEpochs.delete(observedAt);
    }
    const promoted: SubmitEpoch = {
      problemExternalId: message.problemExternalId,
      submitRequestId: message.submitRequestId,
      receivedAt: action.observedAt,
      baseline: action.baseline,
      superseded: false,
      proofObserved: false,
      emitted: false,
    };
    epochs.set(message.submitRequestId, promoted);
    return promoted;
  }

  function candidateForEpoch(
    epoch: SubmitEpoch,
    observation: ArmedVerdictObservation,
    observedAt: string,
  ): AttemptCaptureRuntimeMessage[] {
    if (!epoch.confirmedAt || epoch.emitted || !epoch.proofObserved) return [];
    if (!observation.available || observation.verdict === null || observation.surface === undefined) {
      return [];
    }
    const observedMs = Date.parse(observedAt);
    const confirmedMs = Date.parse(epoch.confirmedAt);
    if (!Number.isFinite(observedMs) || !Number.isFinite(confirmedMs) || observedMs < confirmedMs) {
      reportDiagnostic("verdict_candidate_chronology_mismatch");
      return [];
    }
    const detected = state.detected;
    if (detected === null || detected.platform !== "leetcode"
      || detected.problemExternalId !== epoch.problemExternalId) return [];
    epochs.set(epoch.submitRequestId, { ...epoch, emitted: true });
    return [{
      type: "VERDICT_CANDIDATE_OBSERVED",
      candidate: {
        installationId: "runtime",
        platform: "leetcode",
        problemExternalId: detected.problemExternalId,
        verdict: observation.verdict,
        observedAt,
        submitRequestId: epoch.submitRequestId,
        transitionEvidence: "same_document_transition",
        ...(dependencies.activeDocumentId === undefined
          ? {}
          : { sourceDocumentId: dependencies.activeDocumentId }),
      },
    }];
  }

  function evaluateArmedEpochs(): readonly AttemptCaptureRuntimeMessage[] {
    if (state.detected === null || state.detected.platform !== "leetcode") return [];
    const armed = [...epochs.values()].filter((epoch) =>
      epoch.problemExternalId === state.detected?.problemExternalId);
    if (armed.length === 0) return [];
    const observation = armedObservation();
    if (!observation.available) return [];
    const messages: AttemptCaptureRuntimeMessage[] = [];
    for (const epoch of armed) {
      if (epoch.superseded || epoch.emitted) continue;
      if (!epoch.baseline.captured || epoch.baseline.surface === undefined) continue;
      const verdictChanged = epoch.baseline.verdict !== observation.verdict;
      // An adapter-owned surface replacement is proof only when the current
      // observation still exposes a narrow DOM Element. DTOs, wrappers,
      // document/body nodes, and other invalid surfaces fail closed rather
      // than turning an unavailable observation into transition evidence.
      const surfaceChanged = observation.surface !== undefined
        && epoch.baseline.surface !== observation.surface;
      const meaningful = verdictChanged || surfaceChanged;
      if (meaningful && !epoch.proofObserved) {
        epochs.set(epoch.submitRequestId, { ...epoch, proofObserved: true });
      }
      if (meaningful || epoch.proofObserved) {
        const observedAt = canonicalNow(dependencies);
        const current = epochs.get(epoch.submitRequestId);
        if (current !== undefined) {
          messages.push(...candidateForEpoch(
            { ...current, proofObserved: current.proofObserved || meaningful },
            observation,
            observedAt,
          ));
        }
      }
    }
    return messages;
  }

  function recordUiHint(): readonly UiHintMessage[] {
    const detected = state.detected;
    if (detected === null) return [];
    const observedAt = dependencies.now();
    if (detected.platform === "leetcode") {
      pruneExpiredEpochs(observedAt);
      while (actionEpochs.size >= SUBMIT_EPOCH_MAX_ENTRIES) {
        const oldest = actionEpochs.keys().next().value;
        if (typeof oldest !== "string") break;
        actionEpochs.delete(oldest);
      }
      actionEpochSequence += 1;
      actionEpochs.set(`${observedAt}#${actionEpochSequence}`, {
        problemExternalId: detected.problemExternalId,
        observedAt,
        baseline: baselineFromObservation(),
      });
    }
    return [{
      type: "UI_HINT_OBSERVED",
      hint: {
        schemaVersion: 1,
        tier: "E0",
        kind: "ui_hint",
        platform: detected.platform,
        problemExternalId: detected.problemExternalId,
        observedAt,
      },
    }];
  }

  function clearVerdictTransitions(): void {
    state = {
      ...state,
      lastExactResultActive: undefined,
      lastExactResultVerdict: undefined,
    };
  }

  function evaluateVerdictCandidate(): readonly AttemptCaptureRuntimeMessage[] {
    if (state.detected === null) return [];
    const detected = state.detected;
    const snapshot = currentVerdictSnapshot();
    const exactResult = dependencies.exactResultPage(state.detected);

    // Null/Waiting/Judging phase: always recorded as a transition witness.
    if (snapshot === null || snapshot.verdict === null) {
      if (exactResult === false) {
        state = { ...state, lastVerdictSnapshot: snapshot === null
          ? undefined
          : { verdict: snapshot.verdict, observedAt: dependencies.now() } };
        return [];
      }
      state = {
        ...state,
        lastVerdictSnapshot: snapshot === null
          ? undefined
          : { verdict: snapshot.verdict, observedAt: dependencies.now() },
        lastExactResultActive: exactResult,
        lastExactResultVerdict: undefined,
      };
      return [];
    }

    if (exactResult === true && state.lastExactResultActive !== true) {
      state = {
        ...state,
        lastExactResultActive: true,
        lastExactResultVerdict: snapshot.verdict,
        lastVerdictSnapshot: { verdict: snapshot.verdict, observedAt: dependencies.now() },
      };
      return [{
        type: "VERDICT_CANDIDATE_OBSERVED",
        candidate: {
          installationId: "runtime",
          platform: detected.platform,
          problemExternalId: detected.problemExternalId,
          verdict: snapshot.verdict,
          observedAt: dependencies.now(),
          transitionEvidence: "exact_result_document",
          ...(snapshot.sourceDocumentId === undefined && dependencies.activeDocumentId === undefined
            ? {}
            : { sourceDocumentId: snapshot.sourceDocumentId ?? dependencies.activeDocumentId ?? "" }),
        },
      }];
    }

    if (exactResult === true
      && state.lastExactResultVerdict !== snapshot.verdict
      && state.lastVerdictSnapshot?.verdict === null) {
      state = {
        ...state,
        lastExactResultActive: true,
        lastExactResultVerdict: snapshot.verdict,
        lastVerdictSnapshot: { verdict: snapshot.verdict, observedAt: dependencies.now() },
      };
      return [{
        type: "VERDICT_CANDIDATE_OBSERVED",
        candidate: {
          installationId: "runtime",
          platform: detected.platform,
          problemExternalId: detected.problemExternalId,
          verdict: snapshot.verdict,
          observedAt: dependencies.now(),
          transitionEvidence: "exact_result_document",
          ...(snapshot.sourceDocumentId === undefined && dependencies.activeDocumentId === undefined
            ? {}
            : { sourceDocumentId: snapshot.sourceDocumentId ?? dependencies.activeDocumentId ?? "" }),
        },
      }];
    }

    if (state.lastExactResultActive === true) {
      state = { ...state, lastVerdictSnapshot: { verdict: snapshot.verdict, observedAt: dependencies.now() } };
      return [];
    }

    const last = state.lastVerdictSnapshot;
    if (last === undefined) {
      state = { ...state, lastVerdictSnapshot: { verdict: snapshot.verdict, observedAt: dependencies.now() } };
      return [];
    }

    if (last.verdict === snapshot.verdict) return [];

    state = {
      ...state,
      lastVerdictSnapshot: { verdict: snapshot.verdict, observedAt: dependencies.now() },
    };
    return [{
      type: "VERDICT_CANDIDATE_OBSERVED",
      candidate: {
        installationId: "runtime",
        platform: detected.platform,
        problemExternalId: detected.problemExternalId,
        verdict: snapshot.verdict,
        observedAt: dependencies.now(),
        transitionEvidence: "same_document_transition",
        ...(snapshot.sourceDocumentId === undefined && dependencies.activeDocumentId === undefined
          ? {}
          : { sourceDocumentId: snapshot.sourceDocumentId ?? dependencies.activeDocumentId ?? "" }),
      },
    }];
  }

  function controlMessageReceived(message: unknown): readonly AttemptCaptureRuntimeMessage[] {
    pendingDiagnostic = undefined;
    pruneExpiredEpochs();
    const parsed = parseLeetCodeSubmitEpochControlMessage(message);
    if (!parsed.ok) {
      reportDiagnostic(parsed.reason);
      return [];
    }
    // A submit can race the first content tick.  Reconcile the current
    // document before STARTED attempts its one allowed baseline capture.
    observeDetectedProblem();
    const value = parsed.value;
    if (value.type === LEETCODE_SUBMIT_EPOCH_STARTED) {
      addStartedEpoch(value);
      return [];
    }

    const epoch = epochs.get(value.submitRequestId) ?? promoteActionEpoch(value);
    if (epoch === undefined) {
      return [];
    }
    if (epoch.superseded) {
      reportDiagnostic("epoch_started_missing");
      return [];
    }
    if (epoch.problemExternalId !== value.problemExternalId) {
      reportDiagnostic("epoch_identity_conflict");
      return [];
    }
    if (epoch.confirmedAt !== undefined) {
      if (epoch.confirmedAt !== value.confirmedAt) reportDiagnostic("epoch_timestamp_conflict");
      return [];
    }
    if (Date.parse(value.confirmedAt) < Date.parse(epoch.receivedAt)) {
      reportDiagnostic("epoch_timestamp_conflict");
      return [];
    }
    if (!epoch.baseline.captured || epoch.baseline.surface === undefined) {
      reportDiagnostic("epoch_baseline_missing");
      epochs.set(value.submitRequestId, { ...epoch, confirmedAt: value.confirmedAt });
      return [];
    }
    const confirmed = { ...epoch, confirmedAt: value.confirmedAt };
    epochs.set(value.submitRequestId, confirmed);
    const messages = evaluateArmedEpochs();
    if (messages.length === 0 && !confirmed.proofObserved) {
      reportDiagnostic("epoch_result_surface_unchanged");
    }
    return messages;
  }

  function takeControlDiagnostic(): SubmitEpochDiagnostic | undefined {
    const diagnostic = pendingDiagnostic;
    pendingDiagnostic = undefined;
    return diagnostic;
  }

  function controlMessageResponse(): SubmitEpochControlResponse {
    const diagnostic = takeControlDiagnostic();
    return diagnostic === undefined
      ? { ok: true }
      : diagnosticSubmitEpochResponse(diagnostic);
  }

  return {
    start: () => {
      if (epochs.size > 0 || actionEpochs.size > 0) pruneExpiredEpochs();
      observeDetectedProblem();
      clearVerdictTransitions();
      return evaluateVerdictCandidate();
    },
    locationObserved: () => {
      if (epochs.size > 0 || actionEpochs.size > 0) pruneExpiredEpochs();
      // Strict identity reconciliation preserves a same-problem epoch. Null,
      // ambiguous, unsupported, or cross-problem detection still clears it.
      observeDetectedProblem();
      clearVerdictTransitions();
      state = { ...state, lastVerdictSnapshot: undefined };
      const armed = evaluateArmedEpochs();
      if (armed.length > 0) return armed;
      // An armed request owns the transition; never emit an unbound legacy
      // candidate while its bounded marker is present.
      return hasEpochMarkerForDetectedProblem() ? [] : evaluateVerdictCandidate();
    },
    documentMutated: () => {
      if (epochs.size > 0 || actionEpochs.size > 0) pruneExpiredEpochs();
      observeDetectedProblem();
      const armed = evaluateArmedEpochs();
      if (armed.length > 0) return armed;
      const hasEpochMarker = hasEpochMarkerForDetectedProblem();
      // An armed request owns transition evaluation.  Do not allow legacy
      // same-text dedupe to turn a post-E1 observation into an unbound one.
      // Superseded/terminal markers also block legacy evaluation until their
      // bounded TTL expires or page lifecycle invalidation clears them.
      return hasEpochMarker ? [] : evaluateVerdictCandidate();
    },
    uiHintObserved: () => recordUiHint(),
    uiHintVisible: () => recordUiHint(),
    pageHidden: () => {
      clearEpochs();
      clearVerdictTransitions();
      state = { ...state, lastVerdictSnapshot: undefined };
      return [];
    },
    pageShown: () => {
      clearEpochs();
      observeDetectedProblem();
      clearVerdictTransitions();
      state = { ...state, lastVerdictSnapshot: undefined };
      return evaluateVerdictCandidate();
    },
    controlMessageReceived,
    takeControlDiagnostic,
    controlMessageResponse,
  };
}
